"""phase2 vpn mesh

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 15:50:59.606315
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_peers',
    sa.Column('device_a_id', sa.Uuid(), nullable=False),
    sa.Column('device_b_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('psk_enc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_handshake_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('rx_bytes', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tx_bytes', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_a_id'], ['devices.id'], name=op.f('fk_vpn_peers_device_a_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_b_id'], ['devices.id'], name=op.f('fk_vpn_peers_device_b_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_vpn_peers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vpn_peers')),
    sa.UniqueConstraint('device_a_id', 'device_b_id', name='uq_vpn_peers_pair')
    )
    op.create_index(op.f('ix_vpn_peers_device_a_id'), 'vpn_peers', ['device_a_id'], unique=False)
    op.create_index(op.f('ix_vpn_peers_device_b_id'), 'vpn_peers', ['device_b_id'], unique=False)
    op.create_index(op.f('ix_vpn_peers_tenant_id'), 'vpn_peers', ['tenant_id'], unique=False)
    op.add_column('devices', sa.Column('mesh_ip', sa.String(length=45), nullable=True))
    op.add_column('devices', sa.Column('mesh_public_key', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('mesh_endpoint', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'mesh_endpoint')
    op.drop_column('devices', 'mesh_public_key')
    op.drop_column('devices', 'mesh_ip')
    op.drop_index(op.f('ix_vpn_peers_tenant_id'), table_name='vpn_peers')
    op.drop_index(op.f('ix_vpn_peers_device_b_id'), table_name='vpn_peers')
    op.drop_index(op.f('ix_vpn_peers_device_a_id'), table_name='vpn_peers')
    op.drop_table('vpn_peers')
    # ### end Alembic commands ###
