"""phase3 wan links

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 15:55:07.888604
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wan_links',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('interface', sa.String(length=100), nullable=False),
    sa.Column('gateway', sa.String(length=100), nullable=False),
    sa.Column('resolved_gateway', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=10), nullable=False),
    sa.Column('check_target', sa.String(length=255), nullable=False),
    sa.Column('check_interval_s', sa.Integer(), nullable=False),
    sa.Column('check_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('loss_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('latency_threshold_ms', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_loss_pct', sa.Float(), nullable=True),
    sa.Column('last_check_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_change_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_wan_links_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wan_links_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wan_links')),
    sa.UniqueConstraint('device_id', 'slot', name='uq_wan_links_device_slot')
    )
    op.create_index(op.f('ix_wan_links_device_id'), 'wan_links', ['device_id'], unique=False)
    op.create_index(op.f('ix_wan_links_tenant_id'), 'wan_links', ['tenant_id'], unique=False)
    op.add_column('devices', sa.Column('wan_mode', sa.String(length=30), nullable=False, server_default='failover'))
    op.add_column('devices', sa.Column('wan_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'wan_options')
    op.drop_column('devices', 'wan_mode')
    op.drop_index(op.f('ix_wan_links_tenant_id'), table_name='wan_links')
    op.drop_index(op.f('ix_wan_links_device_id'), table_name='wan_links')
    op.drop_table('wan_links')
    # ### end Alembic commands ###
