"""phase5 firewall policies

Revision ID: 0005
Revises: 0003
Create Date: 2026-09-24 16:05:06.778407
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0005'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall_policies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_firewall_policies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firewall_policies'))
    )
    op.create_index(op.f('ix_firewall_policies_tenant_id'), 'firewall_policies', ['tenant_id'], unique=False)
    op.create_table('policy_deployments',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('atomic', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_by', sa.String(length=255), nullable=True),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['firewall_policies.id'], name=op.f('fk_policy_deployments_policy_id_firewall_policies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_policy_deployments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_deployments'))
    )
    op.create_index(op.f('ix_policy_deployments_policy_id'), 'policy_deployments', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_deployments_tenant_id'), 'policy_deployments', ['tenant_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['firewall_policies.id'], name=op.f('fk_policy_versions_policy_id_firewall_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions')),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_versions_policy_version')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_table('policy_assignments',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('deployed_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('deployed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_policy_assignments_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['firewall_policies.id'], name=op.f('fk_policy_assignments_policy_id_firewall_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_policy_assignments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_assignments')),
    sa.UniqueConstraint('policy_id', 'device_id', name='uq_policy_assignments_policy_device')
    )
    op.create_index(op.f('ix_policy_assignments_device_id'), 'policy_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_policy_assignments_policy_id'), 'policy_assignments', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_assignments_tenant_id'), 'policy_assignments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_assignments_tenant_id'), table_name='policy_assignments')
    op.drop_index(op.f('ix_policy_assignments_policy_id'), table_name='policy_assignments')
    op.drop_index(op.f('ix_policy_assignments_device_id'), table_name='policy_assignments')
    op.drop_table('policy_assignments')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_policy_deployments_tenant_id'), table_name='policy_deployments')
    op.drop_index(op.f('ix_policy_deployments_policy_id'), table_name='policy_deployments')
    op.drop_table('policy_deployments')
    op.drop_index(op.f('ix_firewall_policies_tenant_id'), table_name='firewall_policies')
    op.drop_table('firewall_policies')
    # ### end Alembic commands ###
