"""phase6 zero touch

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 16:08:43.880725
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provisioning_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_provisioning_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provisioning_templates'))
    )
    op.create_index(op.f('ix_provisioning_templates_tenant_id'), 'provisioning_templates', ['tenant_id'], unique=False)
    op.add_column('devices', sa.Column('ztp_template_id', sa.Uuid(), nullable=True))
    op.add_column('devices', sa.Column('ztp_state', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('devices', sa.Column('ztp_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    op.create_index(op.f('ix_devices_ztp_template_id'), 'devices', ['ztp_template_id'], unique=False)
    op.create_foreign_key(op.f('fk_devices_ztp_template_id_provisioning_templates'), 'devices', 'provisioning_templates', ['ztp_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_devices_ztp_template_id_provisioning_templates'), 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_ztp_template_id'), table_name='devices')
    op.drop_column('devices', 'ztp_log')
    op.drop_column('devices', 'ztp_state')
    op.drop_column('devices', 'ztp_template_id')
    op.drop_index(op.f('ix_provisioning_templates_tenant_id'), table_name='provisioning_templates')
    op.drop_table('provisioning_templates')
    # ### end Alembic commands ###
