"""phase7 content filter

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-24 16:13:20.122812
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_filter_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nextdns_profile_id', sa.String(length=32), nullable=True),
    sa.Column('categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('services', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('security', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('blocklists', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('denylist', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('allowlist', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('safe_search', sa.Boolean(), nullable=False),
    sa.Column('youtube_restricted', sa.Boolean(), nullable=False),
    sa.Column('block_bypass', sa.Boolean(), nullable=False),
    sa.Column('force_dns', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('synced_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_content_filter_profiles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_filter_profiles'))
    )
    op.create_index(op.f('ix_content_filter_profiles_tenant_id'), 'content_filter_profiles', ['tenant_id'], unique=False)
    op.add_column('sites', sa.Column('content_filter_profile_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_sites_content_filter_profile_id_content_filter_profiles'), 'sites', 'content_filter_profiles', ['content_filter_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sites_content_filter_profile_id_content_filter_profiles'), 'sites', type_='foreignkey')
    op.drop_column('sites', 'content_filter_profile_id')
    op.drop_index(op.f('ix_content_filter_profiles_tenant_id'), table_name='content_filter_profiles')
    op.drop_table('content_filter_profiles')
    # ### end Alembic commands ###
