"""phase8 remote access

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 16:16:43.884613
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_sessions',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('target_port', sa.Integer(), nullable=False),
    sa.Column('listen_port', sa.Integer(), nullable=False),
    sa.Column('allowed_cidr', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ros_username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=255), nullable=True),
    sa.Column('connections', sa.Integer(), nullable=False),
    sa.Column('bytes_in', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bytes_out', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_remote_sessions_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_remote_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_remote_sessions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remote_sessions'))
    )
    op.create_index(op.f('ix_remote_sessions_device_id'), 'remote_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_remote_sessions_listen_port'), 'remote_sessions', ['listen_port'], unique=False)
    op.create_index(op.f('ix_remote_sessions_status'), 'remote_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_remote_sessions_tenant_id'), 'remote_sessions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remote_sessions_tenant_id'), table_name='remote_sessions')
    op.drop_index(op.f('ix_remote_sessions_status'), table_name='remote_sessions')
    op.drop_index(op.f('ix_remote_sessions_listen_port'), table_name='remote_sessions')
    op.drop_index(op.f('ix_remote_sessions_device_id'), table_name='remote_sessions')
    op.drop_table('remote_sessions')
    # ### end Alembic commands ###
