"""phase9 backups firmware

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-24 16:21:44.858369
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware_jobs',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('batch_interval_s', sa.Integer(), nullable=False),
    sa.Column('max_failures', sa.Integer(), nullable=False),
    sa.Column('upgrade_routerboard', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_batch', sa.Integer(), nullable=False),
    sa.Column('next_batch_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_firmware_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firmware_jobs'))
    )
    op.create_index(op.f('ix_firmware_jobs_tenant_id'), 'firmware_jobs', ['tenant_id'], unique=False)
    op.create_table('config_backups',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('routeros_version', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_config_backups_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_config_backups_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_backups'))
    )
    op.create_index(op.f('ix_config_backups_device_id'), 'config_backups', ['device_id'], unique=False)
    op.create_index(op.f('ix_config_backups_sha256'), 'config_backups', ['sha256'], unique=False)
    op.create_index(op.f('ix_config_backups_tenant_id'), 'config_backups', ['tenant_id'], unique=False)
    op.create_table('firmware_job_items',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('from_version', sa.String(length=64), nullable=True),
    sa.Column('to_version', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_firmware_job_items_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['firmware_jobs.id'], name=op.f('fk_firmware_job_items_job_id_firmware_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_firmware_job_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firmware_job_items'))
    )
    op.create_index(op.f('ix_firmware_job_items_device_id'), 'firmware_job_items', ['device_id'], unique=False)
    op.create_index(op.f('ix_firmware_job_items_job_id'), 'firmware_job_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_firmware_job_items_tenant_id'), 'firmware_job_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firmware_job_items_tenant_id'), table_name='firmware_job_items')
    op.drop_index(op.f('ix_firmware_job_items_job_id'), table_name='firmware_job_items')
    op.drop_index(op.f('ix_firmware_job_items_device_id'), table_name='firmware_job_items')
    op.drop_table('firmware_job_items')
    op.drop_index(op.f('ix_config_backups_tenant_id'), table_name='config_backups')
    op.drop_index(op.f('ix_config_backups_sha256'), table_name='config_backups')
    op.drop_index(op.f('ix_config_backups_device_id'), table_name='config_backups')
    op.drop_table('config_backups')
    op.drop_index(op.f('ix_firmware_jobs_tenant_id'), table_name='firmware_jobs')
    op.drop_table('firmware_jobs')
    # ### end Alembic commands ###
