"""phase11 vrrp

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-25 09:58:06.492766
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vrrp_instances',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('interface', sa.String(length=100), nullable=False),
    sa.Column('vrid', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('interval_ms', sa.Integer(), nullable=False),
    sa.Column('preemption', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('vip', sa.String(length=64), nullable=False),
    sa.Column('local_address', sa.String(length=64), nullable=True),
    sa.Column('linked_wan_slot', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('last_change_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_vrrp_instances_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_vrrp_instances_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vrrp_instances')),
    sa.UniqueConstraint('device_id', 'name', name='uq_vrrp_instances_device_name')
    )
    op.create_index(op.f('ix_vrrp_instances_device_id'), 'vrrp_instances', ['device_id'], unique=False)
    op.create_index(op.f('ix_vrrp_instances_tenant_id'), 'vrrp_instances', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vrrp_instances_tenant_id'), table_name='vrrp_instances')
    op.drop_index(op.f('ix_vrrp_instances_device_id'), table_name='vrrp_instances')
    op.drop_table('vrrp_instances')
    # ### end Alembic commands ###
