"""phase11 wan backup active

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-25 10:03:19.283155
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wan_links', sa.Column('active_since', app.db.UTCDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wan_links', 'active_since')
    # ### end Alembic commands ###
