"""phase11 wan volume

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-25 10:06:11.536828
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wan_links', sa.Column('monthly_limit_gb', sa.Float(), nullable=True))
    op.add_column('wan_links', sa.Column('vol_month', sa.String(length=7), nullable=True))
    op.add_column('wan_links', sa.Column('vol_bytes', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('wan_links', sa.Column('vol_last_rx', sa.BigInteger(), nullable=True))
    op.add_column('wan_links', sa.Column('vol_last_tx', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wan_links', 'vol_last_tx')
    op.drop_column('wan_links', 'vol_last_rx')
    op.drop_column('wan_links', 'vol_bytes')
    op.drop_column('wan_links', 'vol_month')
    op.drop_column('wan_links', 'monthly_limit_gb')
    # ### end Alembic commands ###
