"""phase11 alert webhooks

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-25 10:13:46.027165
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0014'
down_revision = '0013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('webhook_url_enc', sa.Text(), nullable=True))
    op.add_column('alert_rules', sa.Column('webhook_format', sa.String(length=20), server_default='generic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'webhook_format')
    op.drop_column('alert_rules', 'webhook_url_enc')
    # ### end Alembic commands ###
