"""tenant timezone

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-25 10:20:50.255432
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0015'
down_revision = '0014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('timezone', sa.String(length=64), server_default='Europe/Vienna', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'timezone')
    # ### end Alembic commands ###
