"""device selftest

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-25 19:08:15.077356
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0016'
down_revision = '0015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_selftests',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('ran_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ran_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_selftests_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_device_selftests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_selftests'))
    )
    op.create_index(op.f('ix_device_selftests_device_id'), 'device_selftests', ['device_id'], unique=True)
    op.create_index(op.f('ix_device_selftests_tenant_id'), 'device_selftests', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_selftests_tenant_id'), table_name='device_selftests')
    op.drop_index(op.f('ix_device_selftests_device_id'), table_name='device_selftests')
    op.drop_table('device_selftests')
    # ### end Alembic commands ###
