"""phase14 firewall editor

Revision ID: 0020
Revises: 0019
Create Date: 2026-09-26 19:56:30.092687
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0020'
down_revision = '0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fw_blocks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('nat', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_fw_blocks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fw_blocks'))
    )
    op.create_index(op.f('ix_fw_blocks_seed_key'), 'fw_blocks', ['seed_key'], unique=False)
    op.create_index(op.f('ix_fw_blocks_tenant_id'), 'fw_blocks', ['tenant_id'], unique=False)
    op.create_table('fw_objects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('members', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_fw_objects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fw_objects'))
    )
    op.create_index(op.f('ix_fw_objects_seed_key'), 'fw_objects', ['seed_key'], unique=False)
    op.create_index(op.f('ix_fw_objects_slug'), 'fw_objects', ['slug'], unique=False)
    op.create_index(op.f('ix_fw_objects_tenant_id'), 'fw_objects', ['tenant_id'], unique=False)
    op.create_table('fw_services',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('entries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('members', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_fw_services_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fw_services'))
    )
    op.create_index(op.f('ix_fw_services_seed_key'), 'fw_services', ['seed_key'], unique=False)
    op.create_index(op.f('ix_fw_services_slug'), 'fw_services', ['slug'], unique=False)
    op.create_index(op.f('ix_fw_services_tenant_id'), 'fw_services', ['tenant_id'], unique=False)
    op.create_table('fw_zones',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('management', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_fw_zones_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fw_zones'))
    )
    op.create_index(op.f('ix_fw_zones_seed_key'), 'fw_zones', ['seed_key'], unique=False)
    op.create_index(op.f('ix_fw_zones_slug'), 'fw_zones', ['slug'], unique=False)
    op.create_index(op.f('ix_fw_zones_tenant_id'), 'fw_zones', ['tenant_id'], unique=False)
    op.create_table('device_zone_members',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('interface', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_zone_members_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_device_zone_members_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['fw_zones.id'], name=op.f('fk_device_zone_members_zone_id_fw_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_zone_members')),
    sa.UniqueConstraint('device_id', 'interface', name='uq_device_zone_members_device_iface')
    )
    op.create_index(op.f('ix_device_zone_members_device_id'), 'device_zone_members', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_zone_members_tenant_id'), 'device_zone_members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_zone_members_zone_id'), 'device_zone_members', ['zone_id'], unique=False)
    op.create_table('fw_rule_hits',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('packets', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bytes', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('last_hit_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_fw_rule_hits_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_fw_rule_hits_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fw_rule_hits')),
    sa.UniqueConstraint('device_id', 'key', name='uq_fw_rule_hits_device_key')
    )
    op.create_index(op.f('ix_fw_rule_hits_device_id'), 'fw_rule_hits', ['device_id'], unique=False)
    op.create_index(op.f('ix_fw_rule_hits_key'), 'fw_rule_hits', ['key'], unique=False)
    op.create_index(op.f('ix_fw_rule_hits_tenant_id'), 'fw_rule_hits', ['tenant_id'], unique=False)
    op.add_column('firewall_policies', sa.Column('mode', sa.String(length=10), server_default='expert', nullable=False))
    op.add_column('firewall_policies', sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('policy_versions', sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_versions', 'spec')
    op.drop_column('firewall_policies', 'spec')
    op.drop_column('firewall_policies', 'mode')
    op.drop_index(op.f('ix_fw_rule_hits_tenant_id'), table_name='fw_rule_hits')
    op.drop_index(op.f('ix_fw_rule_hits_key'), table_name='fw_rule_hits')
    op.drop_index(op.f('ix_fw_rule_hits_device_id'), table_name='fw_rule_hits')
    op.drop_table('fw_rule_hits')
    op.drop_index(op.f('ix_device_zone_members_zone_id'), table_name='device_zone_members')
    op.drop_index(op.f('ix_device_zone_members_tenant_id'), table_name='device_zone_members')
    op.drop_index(op.f('ix_device_zone_members_device_id'), table_name='device_zone_members')
    op.drop_table('device_zone_members')
    op.drop_index(op.f('ix_fw_zones_tenant_id'), table_name='fw_zones')
    op.drop_index(op.f('ix_fw_zones_slug'), table_name='fw_zones')
    op.drop_index(op.f('ix_fw_zones_seed_key'), table_name='fw_zones')
    op.drop_table('fw_zones')
    op.drop_index(op.f('ix_fw_services_tenant_id'), table_name='fw_services')
    op.drop_index(op.f('ix_fw_services_slug'), table_name='fw_services')
    op.drop_index(op.f('ix_fw_services_seed_key'), table_name='fw_services')
    op.drop_table('fw_services')
    op.drop_index(op.f('ix_fw_objects_tenant_id'), table_name='fw_objects')
    op.drop_index(op.f('ix_fw_objects_slug'), table_name='fw_objects')
    op.drop_index(op.f('ix_fw_objects_seed_key'), table_name='fw_objects')
    op.drop_table('fw_objects')
    op.drop_index(op.f('ix_fw_blocks_tenant_id'), table_name='fw_blocks')
    op.drop_index(op.f('ix_fw_blocks_seed_key'), table_name='fw_blocks')
    op.drop_table('fw_blocks')
    # ### end Alembic commands ###
