"""phase15 threat feeds

Revision ID: 0021
Revises: 0020
Create Date: 2026-09-26 20:11:56.109759
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0021'
down_revision = '0020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_feeds',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('fmt', sa.String(length=10), nullable=False),
    sa.Column('json_field', sa.String(length=40), nullable=False),
    sa.Column('comment_chars', sa.String(length=10), nullable=False),
    sa.Column('interval_min', sa.Integer(), nullable=False),
    sa.Column('max_entries', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.Column('entries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('entries_hash', sa.String(length=64), nullable=True),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('last_fetch_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_threat_feeds_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_feeds'))
    )
    op.create_index(op.f('ix_threat_feeds_seed_key'), 'threat_feeds', ['seed_key'], unique=False)
    op.create_index(op.f('ix_threat_feeds_slug'), 'threat_feeds', ['slug'], unique=False)
    op.create_index(op.f('ix_threat_feeds_tenant_id'), 'threat_feeds', ['tenant_id'], unique=False)
    op.create_table('threat_feed_assignments',
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('synced_hash', sa.String(length=64), nullable=True),
    sa.Column('synced_count', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_threat_feed_assignments_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_id'], ['threat_feeds.id'], name=op.f('fk_threat_feed_assignments_feed_id_threat_feeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_threat_feed_assignments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_feed_assignments')),
    sa.UniqueConstraint('feed_id', 'device_id', name='uq_threat_feed_assignments_feed_device')
    )
    op.create_index(op.f('ix_threat_feed_assignments_device_id'), 'threat_feed_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_threat_feed_assignments_feed_id'), 'threat_feed_assignments', ['feed_id'], unique=False)
    op.create_index(op.f('ix_threat_feed_assignments_tenant_id'), 'threat_feed_assignments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_feed_assignments_tenant_id'), table_name='threat_feed_assignments')
    op.drop_index(op.f('ix_threat_feed_assignments_feed_id'), table_name='threat_feed_assignments')
    op.drop_index(op.f('ix_threat_feed_assignments_device_id'), table_name='threat_feed_assignments')
    op.drop_table('threat_feed_assignments')
    op.drop_index(op.f('ix_threat_feeds_tenant_id'), table_name='threat_feeds')
    op.drop_index(op.f('ix_threat_feeds_slug'), table_name='threat_feeds')
    op.drop_index(op.f('ix_threat_feeds_seed_key'), table_name='threat_feeds')
    op.drop_table('threat_feeds')
    # ### end Alembic commands ###
