"""phase16 compliance

Revision ID: 0022
Revises: 0021
Create Date: 2026-09-26 20:23:25.305814
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0022'
down_revision = '0021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rule_sets',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_rule_sets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_rule_sets'))
    )
    op.create_index(op.f('ix_compliance_rule_sets_seed_key'), 'compliance_rule_sets', ['seed_key'], unique=False)
    op.create_index(op.f('ix_compliance_rule_sets_tenant_id'), 'compliance_rule_sets', ['tenant_id'], unique=False)
    op.create_table('compliance_assignments',
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['compliance_rule_sets.id'], name=op.f('fk_compliance_assignments_rule_set_id_compliance_rule_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_assignments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_assignments'))
    )
    op.create_index(op.f('ix_compliance_assignments_rule_set_id'), 'compliance_assignments', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_compliance_assignments_tenant_id'), 'compliance_assignments', ['tenant_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('evaluated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=True),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('unknown', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['config_backups.id'], name=op.f('fk_compliance_results_backup_id_config_backups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_compliance_results_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['compliance_rule_sets.id'], name=op.f('fk_compliance_results_rule_set_id_compliance_rule_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_results_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_results'))
    )
    op.create_index(op.f('ix_compliance_results_device_id'), 'compliance_results', ['device_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_evaluated_at'), 'compliance_results', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_compliance_results_rule_set_id'), 'compliance_results', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_tenant_id'), 'compliance_results', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_results_tenant_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_rule_set_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_evaluated_at'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_device_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_compliance_assignments_tenant_id'), table_name='compliance_assignments')
    op.drop_index(op.f('ix_compliance_assignments_rule_set_id'), table_name='compliance_assignments')
    op.drop_table('compliance_assignments')
    op.drop_index(op.f('ix_compliance_rule_sets_tenant_id'), table_name='compliance_rule_sets')
    op.drop_index(op.f('ix_compliance_rule_sets_seed_key'), table_name='compliance_rule_sets')
    op.drop_table('compliance_rule_sets')
    # ### end Alembic commands ###
