"""phase17 scripts

Revision ID: 0023
Revises: 0022
Create Date: 2026-09-26 20:33:00.887088
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0023'
down_revision = '0022'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scripts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripts'))
    )
    op.create_index(op.f('ix_scripts_seed_key'), 'scripts', ['seed_key'], unique=False)
    op.create_index(op.f('ix_scripts_tenant_id'), 'scripts', ['tenant_id'], unique=False)
    op.create_table('script_runs',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('script_id', sa.Uuid(), nullable=True),
    sa.Column('script_name', sa.String(length=100), nullable=False),
    sa.Column('script_version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('max_failures', sa.Integer(), nullable=False),
    sa.Column('current_batch', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_script_runs_script_id_scripts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_script_runs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_runs'))
    )
    op.create_index(op.f('ix_script_runs_script_id'), 'script_runs', ['script_id'], unique=False)
    op.create_index(op.f('ix_script_runs_tenant_id'), 'script_runs', ['tenant_id'], unique=False)
    op.create_table('script_versions',
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_script_versions_script_id_scripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_versions')),
    sa.UniqueConstraint('script_id', 'version', name='uq_script_versions_script_version')
    )
    op.create_index(op.f('ix_script_versions_script_id'), 'script_versions', ['script_id'], unique=False)
    op.create_table('script_run_items',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rendered', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('backup_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['config_backups.id'], name=op.f('fk_script_run_items_backup_id_config_backups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_script_run_items_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['script_runs.id'], name=op.f('fk_script_run_items_run_id_script_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_script_run_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_run_items'))
    )
    op.create_index(op.f('ix_script_run_items_device_id'), 'script_run_items', ['device_id'], unique=False)
    op.create_index(op.f('ix_script_run_items_run_id'), 'script_run_items', ['run_id'], unique=False)
    op.create_index(op.f('ix_script_run_items_tenant_id'), 'script_run_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_run_items_tenant_id'), table_name='script_run_items')
    op.drop_index(op.f('ix_script_run_items_run_id'), table_name='script_run_items')
    op.drop_index(op.f('ix_script_run_items_device_id'), table_name='script_run_items')
    op.drop_table('script_run_items')
    op.drop_index(op.f('ix_script_versions_script_id'), table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index(op.f('ix_script_runs_tenant_id'), table_name='script_runs')
    op.drop_index(op.f('ix_script_runs_script_id'), table_name='script_runs')
    op.drop_table('script_runs')
    op.drop_index(op.f('ix_scripts_tenant_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_seed_key'), table_name='scripts')
    op.drop_table('scripts')
    # ### end Alembic commands ###
