"""phase18 operations

Revision ID: 0024
Revises: 0023
Create Date: 2026-09-26 20:44:37.954048
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0024'
down_revision = '0023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_syslog',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('applied_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_syslog_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_device_syslog_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_syslog')),
    sa.UniqueConstraint('device_id', name=op.f('uq_device_syslog_device_id'))
    )
    op.create_index(op.f('ix_device_syslog_tenant_id'), 'device_syslog', ['tenant_id'], unique=False)
    op.create_table('maintenance_windows',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('start_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('weekdays', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('suppress_alerts', sa.Boolean(), nullable=False),
    sa.Column('firmware_allowed', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_maintenance_windows_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_maintenance_windows_site_id_sites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_maintenance_windows_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_windows'))
    )
    op.create_index(op.f('ix_maintenance_windows_device_id'), 'maintenance_windows', ['device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_windows_site_id'), 'maintenance_windows', ['site_id'], unique=False)
    op.create_index(op.f('ix_maintenance_windows_tenant_id'), 'maintenance_windows', ['tenant_id'], unique=False)
    op.create_table('syslog_messages',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('facility', sa.Integer(), nullable=True),
    sa.Column('topics', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_syslog_messages_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_syslog_messages_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_syslog_messages'))
    )
    op.create_index('ix_syslog_messages_device_time', 'syslog_messages', ['device_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_syslog_messages_received_at'), 'syslog_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_syslog_messages_tenant_id'), 'syslog_messages', ['tenant_id'], unique=False)
    op.create_table('speedtest_results',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('wan_link_id', sa.Uuid(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('down_mbps', sa.Float(), nullable=True),
    sa.Column('up_mbps', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('bytes_estimated', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_speedtest_results_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_speedtest_results_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wan_link_id'], ['wan_links.id'], name=op.f('fk_speedtest_results_wan_link_id_wan_links'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speedtest_results'))
    )
    op.create_index(op.f('ix_speedtest_results_device_id'), 'speedtest_results', ['device_id'], unique=False)
    op.create_index(op.f('ix_speedtest_results_tenant_id'), 'speedtest_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_speedtest_results_wan_link_id'), 'speedtest_results', ['wan_link_id'], unique=False)
    op.add_column('alerts', sa.Column('suppressed_reason', sa.String(length=250), nullable=True))
    op.add_column('firmware_jobs', sa.Column('only_in_window', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('wan_links', sa.Column('speedtest_weekly', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wan_links', 'speedtest_weekly')
    op.drop_column('firmware_jobs', 'only_in_window')
    op.drop_column('alerts', 'suppressed_reason')
    op.drop_index(op.f('ix_speedtest_results_wan_link_id'), table_name='speedtest_results')
    op.drop_index(op.f('ix_speedtest_results_tenant_id'), table_name='speedtest_results')
    op.drop_index(op.f('ix_speedtest_results_device_id'), table_name='speedtest_results')
    op.drop_table('speedtest_results')
    op.drop_index(op.f('ix_syslog_messages_tenant_id'), table_name='syslog_messages')
    op.drop_index(op.f('ix_syslog_messages_received_at'), table_name='syslog_messages')
    op.drop_index('ix_syslog_messages_device_time', table_name='syslog_messages')
    op.drop_table('syslog_messages')
    op.drop_index(op.f('ix_maintenance_windows_tenant_id'), table_name='maintenance_windows')
    op.drop_index(op.f('ix_maintenance_windows_site_id'), table_name='maintenance_windows')
    op.drop_index(op.f('ix_maintenance_windows_device_id'), table_name='maintenance_windows')
    op.drop_table('maintenance_windows')
    op.drop_index(op.f('ix_device_syslog_tenant_id'), table_name='device_syslog')
    op.drop_table('device_syslog')
    # ### end Alembic commands ###
