"""phase19 wlan

Revision ID: 0025
Revises: 0024
Create Date: 2026-09-26 21:00:38.579947
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0025'
down_revision = '0024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wlan_profiles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ssid', sa.String(length=32), nullable=False),
    sa.Column('security', sa.String(length=20), nullable=False),
    sa.Column('passphrase_enc', sa.Text(), nullable=True),
    sa.Column('radius_server', sa.String(length=100), nullable=True),
    sa.Column('radius_port', sa.Integer(), nullable=False),
    sa.Column('radius_secret_enc', sa.Text(), nullable=True),
    sa.Column('band', sa.String(length=10), nullable=False),
    sa.Column('channel_width', sa.String(length=10), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('bridge', sa.String(length=64), nullable=False),
    sa.Column('client_isolation', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('psk_rotate_days', sa.Integer(), nullable=True),
    sa.Column('psk_rotated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wlan_profiles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wlan_profiles')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_wlan_profiles_tenant_slug')
    )
    op.create_index(op.f('ix_wlan_profiles_tenant_id'), 'wlan_profiles', ['tenant_id'], unique=False)
    op.create_table('wlan_assignments',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['wlan_profiles.id'], name=op.f('fk_wlan_assignments_profile_id_wlan_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wlan_assignments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wlan_assignments'))
    )
    op.create_index(op.f('ix_wlan_assignments_profile_id'), 'wlan_assignments', ['profile_id'], unique=False)
    op.create_index(op.f('ix_wlan_assignments_tenant_id'), 'wlan_assignments', ['tenant_id'], unique=False)
    op.create_table('wlan_device_states',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('applied_version', sa.Integer(), nullable=True),
    sa.Column('applied_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_wlan_device_states_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['wlan_profiles.id'], name=op.f('fk_wlan_device_states_profile_id_wlan_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wlan_device_states_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wlan_device_states')),
    sa.UniqueConstraint('device_id', 'profile_id', name='uq_wlan_device_states_device_profile')
    )
    op.create_index(op.f('ix_wlan_device_states_device_id'), 'wlan_device_states', ['device_id'], unique=False)
    op.create_index(op.f('ix_wlan_device_states_profile_id'), 'wlan_device_states', ['profile_id'], unique=False)
    op.create_index(op.f('ix_wlan_device_states_tenant_id'), 'wlan_device_states', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('country_code', sa.String(length=2), server_default='AT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'country_code')
    op.drop_index(op.f('ix_wlan_device_states_tenant_id'), table_name='wlan_device_states')
    op.drop_index(op.f('ix_wlan_device_states_profile_id'), table_name='wlan_device_states')
    op.drop_index(op.f('ix_wlan_device_states_device_id'), table_name='wlan_device_states')
    op.drop_table('wlan_device_states')
    op.drop_index(op.f('ix_wlan_assignments_tenant_id'), table_name='wlan_assignments')
    op.drop_index(op.f('ix_wlan_assignments_profile_id'), table_name='wlan_assignments')
    op.drop_table('wlan_assignments')
    op.drop_index(op.f('ix_wlan_profiles_tenant_id'), table_name='wlan_profiles')
    op.drop_table('wlan_profiles')
    # ### end Alembic commands ###
