"""phase20 hotspot

Revision ID: 0026
Revises: 0025
Create Date: 2026-09-26 21:13:37.018135
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0026'
down_revision = '0025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotspot_portals',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.Column('login_type', sa.String(length=10), nullable=False),
    sa.Column('design', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('texts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('terms_required', sa.Boolean(), nullable=False),
    sa.Column('form_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('custom_files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_hotspot_portals_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotspot_portals'))
    )
    op.create_index(op.f('ix_hotspot_portals_seed_key'), 'hotspot_portals', ['seed_key'], unique=False)
    op.create_index(op.f('ix_hotspot_portals_tenant_id'), 'hotspot_portals', ['tenant_id'], unique=False)
    op.create_table('voucher_profiles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('validity_min', sa.Integer(), nullable=False),
    sa.Column('data_limit_mb', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.String(length=40), nullable=True),
    sa.Column('shared_users', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_voucher_profiles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voucher_profiles'))
    )
    op.create_index(op.f('ix_voucher_profiles_tenant_id'), 'voucher_profiles', ['tenant_id'], unique=False)
    op.create_table('hotspot_instances',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('portal_id', sa.Uuid(), nullable=False),
    sa.Column('interface', sa.String(length=64), nullable=False),
    sa.Column('hotspot_address', sa.String(length=64), nullable=True),
    sa.Column('dns_name', sa.String(length=200), nullable=True),
    sa.Column('walled_garden', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('session_timeout_min', sa.Integer(), nullable=False),
    sa.Column('idle_timeout_min', sa.Integer(), nullable=False),
    sa.Column('rate_limit', sa.String(length=40), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('applied_version', sa.Integer(), nullable=True),
    sa.Column('applied_portal_version', sa.Integer(), nullable=True),
    sa.Column('applied_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_hotspot_instances_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_id'], ['hotspot_portals.id'], name=op.f('fk_hotspot_instances_portal_id_hotspot_portals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_hotspot_instances_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotspot_instances')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_hotspot_instances_tenant_slug')
    )
    op.create_index(op.f('ix_hotspot_instances_device_id'), 'hotspot_instances', ['device_id'], unique=False)
    op.create_index(op.f('ix_hotspot_instances_portal_id'), 'hotspot_instances', ['portal_id'], unique=False)
    op.create_index(op.f('ix_hotspot_instances_tenant_id'), 'hotspot_instances', ['tenant_id'], unique=False)
    op.create_table('guest_registrations',
    sa.Column('instance_id', sa.Uuid(), nullable=True),
    sa.Column('portal_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['hotspot_instances.id'], name=op.f('fk_guest_registrations_instance_id_hotspot_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_id'], ['hotspot_portals.id'], name=op.f('fk_guest_registrations_portal_id_hotspot_portals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_guest_registrations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_registrations'))
    )
    op.create_index(op.f('ix_guest_registrations_instance_id'), 'guest_registrations', ['instance_id'], unique=False)
    op.create_index(op.f('ix_guest_registrations_tenant_id'), 'guest_registrations', ['tenant_id'], unique=False)
    op.create_table('voucher_batches',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['hotspot_instances.id'], name=op.f('fk_voucher_batches_instance_id_hotspot_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['voucher_profiles.id'], name=op.f('fk_voucher_batches_profile_id_voucher_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_voucher_batches_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voucher_batches'))
    )
    op.create_index(op.f('ix_voucher_batches_instance_id'), 'voucher_batches', ['instance_id'], unique=False)
    op.create_index(op.f('ix_voucher_batches_profile_id'), 'voucher_batches', ['profile_id'], unique=False)
    op.create_index(op.f('ix_voucher_batches_tenant_id'), 'voucher_batches', ['tenant_id'], unique=False)
    op.create_table('vouchers',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('pushed', sa.Boolean(), nullable=False),
    sa.Column('first_used_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('uptime_s', sa.Integer(), nullable=False),
    sa.Column('bytes_total', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['voucher_batches.id'], name=op.f('fk_vouchers_batch_id_voucher_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['hotspot_instances.id'], name=op.f('fk_vouchers_instance_id_hotspot_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['voucher_profiles.id'], name=op.f('fk_vouchers_profile_id_voucher_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_vouchers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vouchers')),
    sa.UniqueConstraint('instance_id', 'code', name='uq_vouchers_instance_code')
    )
    op.create_index(op.f('ix_vouchers_batch_id'), 'vouchers', ['batch_id'], unique=False)
    op.create_index(op.f('ix_vouchers_instance_id'), 'vouchers', ['instance_id'], unique=False)
    op.create_index(op.f('ix_vouchers_tenant_id'), 'vouchers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vouchers_tenant_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_instance_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_batch_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_voucher_batches_tenant_id'), table_name='voucher_batches')
    op.drop_index(op.f('ix_voucher_batches_profile_id'), table_name='voucher_batches')
    op.drop_index(op.f('ix_voucher_batches_instance_id'), table_name='voucher_batches')
    op.drop_table('voucher_batches')
    op.drop_index(op.f('ix_guest_registrations_tenant_id'), table_name='guest_registrations')
    op.drop_index(op.f('ix_guest_registrations_instance_id'), table_name='guest_registrations')
    op.drop_table('guest_registrations')
    op.drop_index(op.f('ix_hotspot_instances_tenant_id'), table_name='hotspot_instances')
    op.drop_index(op.f('ix_hotspot_instances_portal_id'), table_name='hotspot_instances')
    op.drop_index(op.f('ix_hotspot_instances_device_id'), table_name='hotspot_instances')
    op.drop_table('hotspot_instances')
    op.drop_index(op.f('ix_voucher_profiles_tenant_id'), table_name='voucher_profiles')
    op.drop_table('voucher_profiles')
    op.drop_index(op.f('ix_hotspot_portals_tenant_id'), table_name='hotspot_portals')
    op.drop_index(op.f('ix_hotspot_portals_seed_key'), table_name='hotspot_portals')
    op.drop_table('hotspot_portals')
    # ### end Alembic commands ###
