"""defconf disabled

Revision ID: 0027
Revises: 0026
Create Date: 2026-09-27 00:15:26.130454
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0027'
down_revision = '0026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fw_defconf_disabled',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('chain', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['policy_deployments.id'], name=op.f('fk_fw_defconf_disabled_deployment_id_policy_deployments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_fw_defconf_disabled_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_fw_defconf_disabled_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fw_defconf_disabled')),
    sa.UniqueConstraint('device_id', 'rule_id', name='uq_fw_defconf_disabled_device_rule')
    )
    op.create_index(op.f('ix_fw_defconf_disabled_device_id'), 'fw_defconf_disabled', ['device_id'], unique=False)
    op.create_index(op.f('ix_fw_defconf_disabled_tenant_id'), 'fw_defconf_disabled', ['tenant_id'], unique=False)
    op.add_column('policy_deployments', sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_deployments', 'options')
    op.drop_index(op.f('ix_fw_defconf_disabled_tenant_id'), table_name='fw_defconf_disabled')
    op.drop_index(op.f('ix_fw_defconf_disabled_device_id'), table_name='fw_defconf_disabled')
    op.drop_table('fw_defconf_disabled')
    # ### end Alembic commands ###
