"""defconf fingerprint

Revision ID: 0028
Revises: 0027
Create Date: 2026-09-27 05:09:01.234906
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0028'
down_revision = '0027'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fw_defconf_disabled', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('fw_defconf_disabled', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fw_defconf_disabled', 'status')
    op.drop_column('fw_defconf_disabled', 'fingerprint')
    # ### end Alembic commands ###
