"""offboarding archives

Revision ID: 0029
Revises: 0028
Create Date: 2026-09-27 05:19:41.484896
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0029'
down_revision = '0028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offboarding_archives',
    sa.Column('device_name', sa.String(length=200), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('routeros_version', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('backup_created_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_offboarding_archives_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offboarding_archives'))
    )
    op.create_index(op.f('ix_offboarding_archives_expires_at'), 'offboarding_archives', ['expires_at'], unique=False)
    op.create_index(op.f('ix_offboarding_archives_tenant_id'), 'offboarding_archives', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offboarding_archives_tenant_id'), table_name='offboarding_archives')
    op.drop_index(op.f('ix_offboarding_archives_expires_at'), table_name='offboarding_archives')
    op.drop_table('offboarding_archives')
    # ### end Alembic commands ###
