"""platform backups

Revision ID: 0030
Revises: 0029
Create Date: 2026-09-27 05:43:03.288874
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0030'
down_revision = '0029'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_alerts',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fired_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_alerts'))
    )
    op.create_index(op.f('ix_platform_alerts_status'), 'platform_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_platform_alerts_type'), 'platform_alerts', ['type'], unique=False)
    op.create_table('platform_backups',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('size', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('contents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_by', sa.String(length=255), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_backups'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_backups')
    op.drop_index(op.f('ix_platform_alerts_type'), table_name='platform_alerts')
    op.drop_index(op.f('ix_platform_alerts_status'), table_name='platform_alerts')
    op.drop_table('platform_alerts')
    # ### end Alembic commands ###
