"""security advisories

Revision ID: 0032
Revises: 0031
Create Date: 2026-09-27 06:06:31.915470
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0032'
down_revision = '0031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_advisories',
    sa.Column('cve', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('function', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('affected_from', sa.String(length=20), nullable=False),
    sa.Column('affected_to', sa.String(length=20), nullable=True),
    sa.Column('fixed_in', sa.String(length=20), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_advisories'))
    )
    op.create_index(op.f('ix_security_advisories_cve'), 'security_advisories', ['cve'], unique=False)
    op.create_index(op.f('ix_security_advisories_seed_key'), 'security_advisories', ['seed_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_advisories_seed_key'), table_name='security_advisories')
    op.drop_index(op.f('ix_security_advisories_cve'), table_name='security_advisories')
    op.drop_table('security_advisories')
    # ### end Alembic commands ###
