"""local access and api tokens

Revision ID: 0033
Revises: 0032
Create Date: 2026-09-27 06:23:39.454087
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0033'
down_revision = '0032'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_index(op.f('ix_api_tokens_prefix'), 'api_tokens', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_tokens_tenant_id'), 'api_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('local_access',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.Column('password_set_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('rotate_due_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('networks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('interfaces', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('manual_networks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('service_port', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mac_winbox_before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('services_before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('applied_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_local_access_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_local_access_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_access')),
    sa.UniqueConstraint('device_id', name='uq_local_access_device')
    )
    op.create_index(op.f('ix_local_access_device_id'), 'local_access', ['device_id'], unique=False)
    op.create_index(op.f('ix_local_access_tenant_id'), 'local_access', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_local_access_tenant_id'), table_name='local_access')
    op.drop_index(op.f('ix_local_access_device_id'), table_name='local_access')
    op.drop_table('local_access')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_tenant_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_prefix'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
