"""neighbors flows inventory

Revision ID: 0034
Revises: 0033
Create Date: 2026-09-27 06:41:33.686351
"""
from alembic import op
import sqlalchemy as sa
import app.db
from sqlalchemy.dialects import postgresql

revision = '0034'
down_revision = '0033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eol_models',
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('since', sa.Date(), nullable=True),
    sa.Column('successor', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eol_models'))
    )
    op.create_index(op.f('ix_eol_models_model'), 'eol_models', ['model'], unique=False)
    op.create_index(op.f('ix_eol_models_seed_key'), 'eol_models', ['seed_key'], unique=False)
    op.create_table('device_flows',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interfaces', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ifindex', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_flows_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_device_flows_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_flows')),
    sa.UniqueConstraint('device_id', name='uq_device_flows_device')
    )
    op.create_index(op.f('ix_device_flows_device_id'), 'device_flows', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_flows_tenant_id'), 'device_flows', ['tenant_id'], unique=False)
    op.create_table('device_inventory',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_inventory_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_device_inventory_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_inventory')),
    sa.UniqueConstraint('device_id', name='uq_device_inventory_device')
    )
    op.create_index(op.f('ix_device_inventory_device_id'), 'device_inventory', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_inventory_tenant_id'), 'device_inventory', ['tenant_id'], unique=False)
    op.create_table('device_neighbors',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('interface', sa.String(length=100), nullable=True),
    sa.Column('identity', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('seen_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_neighbors_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_device_neighbors_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_neighbors'))
    )
    op.create_index(op.f('ix_device_neighbors_device_id'), 'device_neighbors', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_neighbors_tenant_id'), 'device_neighbors', ['tenant_id'], unique=False)
    op.create_table('flow_aggregates',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('bucket', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('wan', sa.String(length=100), nullable=True),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('peer', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('packets', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_flow_aggregates_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_flow_aggregates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flow_aggregates'))
    )
    op.create_index(op.f('ix_flow_aggregates_bucket'), 'flow_aggregates', ['bucket'], unique=False)
    op.create_index(op.f('ix_flow_aggregates_device_id'), 'flow_aggregates', ['device_id'], unique=False)
    op.create_index(op.f('ix_flow_aggregates_tenant_id'), 'flow_aggregates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_aggregates_tenant_id'), table_name='flow_aggregates')
    op.drop_index(op.f('ix_flow_aggregates_device_id'), table_name='flow_aggregates')
    op.drop_index(op.f('ix_flow_aggregates_bucket'), table_name='flow_aggregates')
    op.drop_table('flow_aggregates')
    op.drop_index(op.f('ix_device_neighbors_tenant_id'), table_name='device_neighbors')
    op.drop_index(op.f('ix_device_neighbors_device_id'), table_name='device_neighbors')
    op.drop_table('device_neighbors')
    op.drop_index(op.f('ix_device_inventory_tenant_id'), table_name='device_inventory')
    op.drop_index(op.f('ix_device_inventory_device_id'), table_name='device_inventory')
    op.drop_table('device_inventory')
    op.drop_index(op.f('ix_device_flows_tenant_id'), table_name='device_flows')
    op.drop_index(op.f('ix_device_flows_device_id'), table_name='device_flows')
    op.drop_table('device_flows')
    op.drop_index(op.f('ix_eol_models_seed_key'), table_name='eol_models')
    op.drop_index(op.f('ix_eol_models_model'), table_name='eol_models')
    op.drop_table('eol_models')
    # ### end Alembic commands ###
